<?php

namespace Database\Seeders;

use Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use DB;
class UsagersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('usagers')->insert([
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309444',
            'password'=>Hash::make('2309444'),
            'email'=>'lawidMocko@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>1,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309445',
            'password'=>Hash::make('2309445'),
            'email'=>'lawidMoco@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>1,
            'role'=>'professeur',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309446',
            'password'=>Hash::make('2309446'),
            'email'=>'lawidMoko@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>1,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309447',
            'password'=>Hash::make('2309444'),
            'email'=>'lawidocko@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>1,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309448',
            'password'=>Hash::make('2309444'),
            'email'=>'lawido@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>1,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309449',
            'password'=>Hash::make('2309444'),
            'email'=>'lawidMoo@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>1,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309450',
            'password'=>Hash::make('2309444'),
            'email'=>'lawidMo@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>2,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309451',
            'password'=>Hash::make('2309444'),
            'email'=>'lawidMc@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>2,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309452',
            'password'=>Hash::make('2309444'),
            'email'=>'lawidMocuo@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>2,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309453',
            'password'=>Hash::make('2309444'),
            'email'=>'lawidMoui@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>2,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        [
            'nom'=>'Lando',
            'prenom'=>'Brayan',
            'matricule'=>'2309454',
            'password'=>Hash::make('2309444'),
            'email'=>'lawidMopu@gmail.com',
            'avatar'=>'etghtegte-674f8f0b7e1f4.jpg',
            'equipe_id'=>2,
            'role'=>'etudiant',
            'professeur_id'=>1
        ],
        ]);
    }
}
